### ISSUE TITLE
createCanvas() does not use its parameters

### ISSUE THREAD

**Issue by MikeyBeez** [pixelkind/p5canvas#31]
I specify a size like (200,200), but createCanvas() uses the whole tab.  When I set background(70, 0, 200); The entire tab is colored purple -- not just a 200 by 200 square.  I don't think this is the expected behavior.   I'm using p5canvas 1.4.1.  BTW, thank you for creating this.  The IDE bundled with P5.js is unusable on a hidpi monitor.   Cheers, and Happy New Year!

**Comment by pixelkind** [comment]
Hej @MikeyBeez,

this is actually the expected behavior. The extension is designed to always fill up the available screen and has a predefined setup method. I am working on an addition to control the size of the canvas yourself if you like too.

Cheers and Happy New Year and I am always happy to hear from users :)

**Comment by wisehackermonkey** [comment]
i would love this feature!

**Comment by pixelkind** [comment]
@wisehackermonkey I am just about to publish the latest version (1.7.0) of p5canvas, which will include this feature :)
